name: flutter_bloc_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  cloud_firestore: ^5.6.10
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.1.1
  timeago: ^3.7.1
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Shatoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
